---
- hosts: all
  become: true
  remote_user: ubuntu
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - apt-transport-https


    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Set permissions for Docker's GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add the Docker repository to Apt sources
      shell: echo "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install the latest version of Docker CE and containerd
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Verify Docker is installed
      command: docker run hello-world
      register: result_install
      failed_when: "'Hello from Docker!' not in result_install.stdout_lines"
      
    - name: Run Docker image from Docker Hub
      shell: docker run -d --rm -p 8081:8081 --name ercli-asi-insurance_cep1 lakanilaw/ercli-asi-insurance_cep1:latest
      register: result_image
      failed_when: result_image.rc != 0
...
